---
title: "STA2201 Lab 1"
author: "Timothy Jordan Regis"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r}
library(dplyr)
library(tidyverse)
library(ggplot2)
```


```{r}
dm <- read_table("https://www.prdh.umontreal.ca/BDLC/data/ont/Mx_1x1.txt", skip = 2, col_types = "dcddd")
head(dm)
dm <- data.frame(dm)

pop <- read_table("https://www.prdh.umontreal.ca/BDLC/data/ont/Population.txt", skip = 2, col_types = "dcddd")
head(pop)
pop <- data.frame(pop)
```

# Q1
```{r}
mort_rates = dm %>% 
  filter(
  Age == 10 | Age == 20 | Age == 30 | Age == 40 
) %>% 
  mutate(
  ratio = Male/Female
)
mort_rates %>% 
  ggplot(aes(y = ratio, x = Year, color = Age)) +
  geom_line()
#plot(mort_rates$ratio, mort_rates$Year, type = "line", color = Age)
```

# Q2
```{r}
max(dm$Female)
```

```{r}
# Highest Absolute
dm %>% group_by(Year) %>% filter(Female == max(Female)) %>% select(Year, Age, Female)
```

# Q3

```{r}
dm %>% 
  group_by(Age) %>% 
  summarise(std_M = sd(Male, na.rm = TRUE), 
            std_F = sd(Female, na.rm = TRUE), 
            std_T = sd(Total, na.rm = TRUE))
```

# Q4

```{r}
dm %>% left_join(y = pop, by = c("Year", "Age")) %>% mutate(
  pw_F = Female.x/Female.y,
  pw_M = Male.x/Male.y
) %>% filter(!is.nan(pw_M) & !is.nan(pw_F) & 
             !is.infinite(pw_M) & !is.infinite(pw_F)) %>% 
  group_by(Year) %>% 
  summarise(avg_F = mean(pw_F, na.rm = TRUE), avg_M = mean(pw_M, na.rm = TRUE)) %>% 
  pivot_longer(cols = c(2:3), names_to = "Sex", values_to = "Average_Rate") %>% 
  ggplot(aes(x = Year, y = Average_Rate, color = Sex)) + geom_line()
```

From the looks of this graph, men tend to see a much higher variability in their death rates, often attaining greater levels than Women.